language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo cli
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "chuanqiong"
  - git config user.email "rubyvirusqq@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/rubyvirus/rubyvirus.github.io.git
